/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Propuesta1RouteImport } from './routes/propuesta-1'
import { Route as IndexRouteImport } from './routes/index'

const Propuesta1Route = Propuesta1RouteImport.update({
  id: '/propuesta-1',
  path: '/propuesta-1',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/propuesta-1': typeof Propuesta1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/propuesta-1': typeof Propuesta1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/propuesta-1': typeof Propuesta1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/propuesta-1'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/propuesta-1'
  id: '__root__' | '/' | '/propuesta-1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Propuesta1Route: typeof Propuesta1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propuesta-1': {
      id: '/propuesta-1'
      path: '/propuesta-1'
      fullPath: '/propuesta-1'
      preLoaderRoute: typeof Propuesta1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Propuesta1Route: Propuesta1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
